### ISSUE TITLE
SilhouetteCameo object has no attribute 'commands'

### ISSUE THREAD

**Issue by tiger12506** [fablabnbg/inkscape-silhouette#147]
![image](https://user-images.githubusercontent.com/1036922/121620933-30773f00-ca39-11eb-8a38-a2c4ce994175.png)
```Exception ignored in: <function SilhouetteCameo.__del__ at 0x0000024d7c911ca0>
Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 496, in __del__
    if self.commands:
AttributeError: 'SilhouetteCameo' object has no attribute 'commands'
__init__() got an unexpected keyword argument 'no_device'
```
Win10 Home, Version 2004, 19041.985
Inkscape 1.1 (c68e22c387, 2021-05-23)
inkscape-silhouette-winpackage_1_25.zip

I tried to see if I can learn anything from Python itself (I don't really know if this is a valid way to run python scripts meant for inkscape plugins...) but that didn't really get me much farther.
![image](https://user-images.githubusercontent.com/1036922/121621835-f313b100-ca3a-11eb-995e-a73ee49d9946.png)

Any ideas?

**Comment by tiger12506** [comment]
Also, the code seems to log messages like "device lookup under windows not tested. Help adding code!", but it seems to find the thing... "Silhouette Cameo found on usb bus=0 addr=1"
"device init under windows not implemented. Help adding code!"

I might be able to help with this... at least I can help with testing.

**Comment by t0b3** [comment]
@tiger12506 does it work with v1.24? if yes, it would be interesting to have your help to do a bisect i.e. starting from a654f738d950d2611479584d753e9f37af97d62f & test which of the upcoming commits broke the things...

**Comment by tiger12506** [comment]
v1.24 gives me this:
![image](https://user-images.githubusercontent.com/1036922/121762771-050e5600-cb06-11eb-9c37-21a738d97546.png)

```Traceback (most recent call last):
  File "sendto_silhouette.py", line 1300, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "sendto_silhouette.py", line 1071, in effect
    state = dev.status()    # hint at loading paper, if not ready.
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 588, in status
    self.send_escape(CMD_ENQ)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 534, in send_escape
    self.write(CMD_ESC + esc)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 472, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 2 bytes failed: r=0
```

I should mention I'm attempting to be a brand new user, so it may not be a regression you're looking for, but a PEBKAC error.

**Comment by tiger12506** [comment]
Looking at #61 and the code for Graphtec.py, I ran this, and it works!
So, I'm not sure why it's not working as an inkscape plugin?

```import usb.core

dev = usb.core.find(idVendor=0x0b4d, idProduct=0x1121)
dev.set_configuration()
cfg = dev.get_active_configuration()
intf = cfg[(0,0)]

ep = usb.util.find_descriptor(
    intf,
    # match the first OUT endpoint
    custom_match = \
    lambda e: \
        usb.util.endpoint_direction(e.bEndpointAddress) == \
        usb.util.ENDPOINT_OUT)
        
def cut_square():
    ep.write('M1000,1000')
    ep.write('D1000,1')
    ep.write('D1,1')
    ep.write('D1,1000')
    ep.write('D1000,1000')
    ep.write('M0,0')
    ep.write('\x04')

cut_square()
```

**Comment by tiger12506** [comment]
Okay, well now I'm good and confused. This seems to work also.
![image](https://user-images.githubusercontent.com/1036922/121765431-bcac6380-cb18-11eb-90fe-191db7532403.png)

I guess based on the error message, the plugin is expecting a response back and it's not forthcoming. This is a SIlhouette Cameo 1 machine. Not sure why it's acting differently when in inkscape compared to running directly in python.

**Comment by tiger12506** [comment]
Ok, I finally got it working in inkscape.
I think the issue is that the plugin expects a certain response from the Silhouette, which maybe isn't the case for a Silhouette Cameo 1? Anyways, I commented out a couple of checks and I got a successful run from within inkscape of an svg.

```diff --git a/silhouette/Graphtec.py b/silhouette/Graphtec.py
index ef7b2b3..056548a 100644
--- a/silhouette/Graphtec.py
+++ b/silhouette/Graphtec.py
@@ -588,7 +588,8 @@ Alternatively, you can add yourself to group 'lp' and logout/login.""" % (self.h
         retry += 1
         msg += 'r'
       elif r <= 0:
-        raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
+#        raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
+        pass
       else:
         retry = 0
       o += r
@@ -693,7 +694,8 @@ Alternatively, you can add yourself to group 'lp' and logout/login.""" % (self.h
       print("usb.core.USBError:", e, file=self.log)
       pass
     if resp[-1] != CMD_ETX[0]:
-      raise ValueError('status response not terminated with 0x03: %s' % (resp[-1]))
+#      raise ValueError('status response not terminated with 0x03: %s' % (resp[-1]))
+        pass
     return RESP_DECODING.get(resp[:-1], resp[:-1])
 
   def get_tool_setup(self):
```

If you need me to test any changes, no problem. I also have access to a Silhouette Cameo 4. Would be really nice to swap between them with them both connected... Even better, to have them both running jobs simultaneously -- not even Silhouette Studio can do that...

**Comment by t0b3** [comment]
@gwhitney would you like to step up to 
- fix this issue related to Cameo1
- add a feature to select among multiple connected usb plotters?
your help would be highly appreciated.

**Comment by t0b3** [comment]
@tiger12506 can you 
a) confirm v1.25 works well on Windows with Cameo 4?
b) test the init sequence from [Commands.md](https://github.com/fablabnbg/inkscape-silhouette/blob/master/Commands.md#typical-sequence) what is the response from Cameo 1?

**Comment by gwhitney** [comment]
> @gwhitney would you like to step up to
> 
>     * fix this issue related to Cameo1
> 
>     * add a feature to select among multiple connected usb plotters?
>       your help would be highly appreciated.

Well, I am a bit confused. Is the initial bug report in this issue connected with running examples/testcut_sq_tr.py ? I cannot find any other occurrence of the string "no_device" in v1.25, and one of the messages at the top is `__init__() got an unexpected keyword argument 'no_device'` If someone can tell me - is there some option in the inkscape_silhouette that offers to do a test cut which then runs through this examples/testcut_sq_tr.py? I was completely unaware of this program, but if either of you can confirm it was run in the case this issue is about and let me know how it is ending up running, I would be happy to debug that and fix it up to run with a Cameo 4. Clearly examples/testcut_sq_try.py needs updating with the latest changes and I overlooked it, my apologies.

As for running with Cameo 1, it's possible that in a few weeks I might be able to get access to a Cameo 1, not sure. I will try, and if I can get my hands on one, I'd be happy to see what's going on. If I don't have one, not sure how I can possibly address issues with using a Cameo 1 with inkscape_silhouette. I will say I do **not** recommend commenting out those checks in the main distribution as a solution!

Finally, about an option to select among multiple devices attached to the same computer: Again, if I get my hands on a second device, I would be happy to work on that; if not, I don't see how I can. But in either case, it would seem to me that should be filed as a separate (enhancement request) issue, and it needs some fleshing out as to how it would work. E.g., possibility 1: In the new logging and dumping screen, when you select a particular hardware model, then inkscape_silhouette preferentially searches for that model and uses one of that model if it finds it. That would be easy to do, and would in a rudimentary fashion allow switching between two devices of different models, but it won't do anything if you have two devices of the same model attached. Possibility 2: Add an option that just lets you specify to use the "nth" device found, which can be set to 1 or 2 or 3 ... That would probably work, but it would be hit or miss; you'd just have to see what device it got to when set to 1, and if you wanted a different one, set it to 2 and see what happens, etc. Pretty clunky. Possibility 3: inkscape_silhouette polls the USB buses before putting up the control dialogue, and gives you a dropdown option to select among any Graphtec devices it has found. That would be the best, of course, but my experience is with patching an existing plugin; I don't really have any idea if the inkscape plugin architecture allows dynamic plugin dialogues, and frankly I'm not too interested in diving in deep to find out, but maybe one of you knows offhand and then I could use your guidance to get something like this done. Possibility 4: In the Preview generated with matplotlib, if more than one device has been discovered, I could put up multiple "Cut" buttons, one for each device. I think I have all the information needed to make something like that work, and it's almost as good as Possibility 3, but it would mean that installing matplotlib would become even more important for inkscape_silhouette's functionality, so the installation procedures should be changed to try to make that happen, which I have to say is not really my forte. So anyhow, clearly there are a number of choices here, and it seems to me this part of the discussion should be moved to its own issue.

**Comment by t0b3** [comment]
> Well, I am a bit confused. Is the initial bug report in this issue connected with running examples/testcut_sq_tr.py ? I cannot find any other occurrence of the string "no_device" in v1.25, and one of the messages at the top is `__init__() got an unexpected keyword argument 'no_device'` If someone can tell me - is there some option in the inkscape_silhouette that offers to do a test cut which then runs through this examples/testcut_sq_tr.py? I was completely unaware of this program, but if either of you can confirm it was run in the case this issue is about and let me know how it is ending up running, I would be happy to debug that and fix it up to run with a Cameo 4. Clearly examples/testcut_sq_try.py needs updating with the latest changes and I overlooked it, my apologies.

@tiger12506 can you explain how to reproduce on Cameo1 with v1.25 and provide the exact procedure and debug the response codes from your plotter?
btw: does this issue reproduce on linux? or does it resolve if you introduce [these lines](https://github.com/fablabnbg/inkscape-silhouette/blob/4e564ffff8f73940e5ed618861fb15f5cdf54fe0/silhouette/Graphtec.py#L473-L477) to your windows device init?
 
> As for running with Cameo 1, it's possible that in a few weeks I might be able to get access to a Cameo 1, not sure. I will try, and if I can get my hands on one, I'd be happy to see what's going on. If I don't have one, not sure how I can possibly address issues with using a Cameo 1 with inkscape_silhouette. I will say I do **not** recommend commenting out those checks in the main distribution as a solution!

@gwhitney totally agree, we would need device specific exceptions based on reproducible behavior.

**Comment by t0b3** [comment]
@tiger12506 I realized the files in the windows .zip were messed up. There is a new .zip online. Please retry this one and report back.

**Comment by tiger12506** [comment]
I tried it out today and everything worked smoothly on tag v1.25, so I was very confused.
However, I just ran a test and it failed with the ValueError: write 2 bytes failed: r=0.

First time around I was following instructions, and replaced the WinUSB driver with libusb-win32 like recommended using ZaDiag.exe. And that's what gave me the issues.

The tests today that ran smoothly out of the box -- I had forgotten to replace the WinUSB driver after running the machine with Silhouette Studio.

So I think that _my_ issues were first by the wrong windows zip t0b3 just mentioned, and then when I switched to symlinks from repo, my issues were caused by libusb-win32, not Cameo1 specifically or inkscape-silhouette.

Is there anything, given that information, that I can help with?
(Edit: I don't really understand the different usb drivers situation well enough to grok what's going on there)

**Comment by tiger12506** [comment]
And after a very long fight getting it fixed to work with Silhouette Studio once again, it refused to work with usb.core or inkscape-silhouette. So I had to install libusb-win32 again. I'm very confused. It might be wise to close this issue for now until I educate myself better. :)

**Comment by gwhitney** [comment]
I know this issue is closed, but I thought I would follow up and mention that unfortunately the "old" Silhouette I do now have access to turns out to be a Cameo 3 (so not really that old after all). So I wouldn't be able to directly help with this, but I should now be able to handle #148 within the next few weeks.

**Comment by t0b3** [comment]
> Ok, I finally got it working in inkscape. I think the issue is that the plugin expects a certain response from the Silhouette, which maybe isn't the case for a Silhouette Cameo 1? Anyways, I commented out a couple of checks and I got a successful run from within inkscape of an svg.
> 
> ```diff
> index ef7b2b3..056548a 100644
> --- a/silhouette/Graphtec.py
> +++ b/silhouette/Graphtec.py
> @@ -588,7 +588,8 @@ Alternatively, you can add yourself to group 'lp' and logout/login.""" % (self.h
>          retry += 1
>          msg += 'r'
>        elif r <= 0:
> -        raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
> +#        raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
> +        pass
>        else:
>          retry = 0
>        o += r
> @@ -693,7 +694,8 @@ Alternatively, you can add yourself to group 'lp' and logout/login.""" % (self.h
>        print("usb.core.USBError:", e, file=self.log)
>        pass
>      if resp[-1] != CMD_ETX[0]:
> -      raise ValueError('status response not terminated with 0x03: %s' % (resp[-1]))
> +#      raise ValueError('status response not terminated with 0x03: %s' % (resp[-1]))
> +        pass
>      return RESP_DECODING.get(resp[:-1], resp[:-1])
>  
>    def get_tool_setup(self):
> ```
> 
> If you need me to test any changes, no problem. I also have access to a Silhouette Cameo 4. Would be really nice to swap between them with them both connected... Even better, to have them both running jobs simultaneously -- not even Silhouette Studio can do that...

@tiger12506 can you tell us how Cameo 4 behaves without theese changes? your answear will be of great help to narrow down the scope of #152
