### PR TITLE
Inkscape v1.00 compatibility updates

### PR DESCRIPTION
**Pull request by uxwalter**
These changes get rid of all* deprecation warnings when running inkscape-silhouette on inkscape version 1.00.

I figured I send this out here for folks that were forced onto inkscape v1 and ran into issues with their silhouette cutter. Since the changes are likely not backwards compatible with 0.92 or even python2 I suspect you don't want to just integrate this. Let's either have a conversation about how to make this acceptable or use it as a simple guide to get the changes made properly by someone else.

It also fixes parts or all of issues #101 and #90, at least for me.

Disclaimers:
* Tested successfully on Inkscape v1.00, python3 and Silhouette Cameo 3. 
* Only tested with my typical workflows
* Didn't touch other files that probably need updating as well (e.g. silhouette_multi.py)
* Not tested on inkscape 0.92 and/or python2

### CODE REVIEW

**Comment by bianchifan** [comment]
System: Ubuntu 20.04, Inkscape 1.0, Python 3, Cameo 2

This should be plotted/cut
Bildschirmfoto von 2020-07-04 11-20-39
...and this was plotted, BLACK = regular plot, RED = with REGMARKS activated
DSC03436
error messages for regular plot
Bildschirmfoto von 2020-07-04 11-48-03
...and for REGMARKS plot
Bildschirmfoto von 2020-07-04 11-49-30

**Comment by uxwalter** [comment]
Pretty sure those warnings come from the master version of Graphtec.py, not the one in this PR. Maybe double check that? While at it also check the version in the "About" tab although the absence of additional warnings suggests you got the correct version of sendto_silhouette.py (i.e., the one from this PR)

**Comment by bianchifan** [comment]
> Pretty sure those warnings come from the master version of Graphtec.py
Yoe*re absolutely right..

> not the one in this PR. Maybe double check that?
What did I?
I followed the three commits you posted above.
I was wondering about no 2 and 3 because they point to the same change in "sendto_silhouette.inx".
I just made a compare regarding your forked master and found the other changes :)

Excuse me please that I didn't notice your fork :(

**Comment by bianchifan** [comment]
Results of my tests with new Graphtec.py:
- deprecation warnings for regular plot are gone
- plot is still the same as above, some objects are missing

Dump with actual PR
Dump_Fox32_decals
To compare... dump with old extention and Inkscape 0.92.5 (Ubuntu 19.10)
Dump_Fox32_decals-0 92 5
OLD extention, because PR extention does not work with Inkscape 0.92.5
_Traceback (most recent call last):
  File "sendto_silhouette.py", line 125, in <module>
    from inkex.paths import CubicSuperPath, Path
ModuleNotFoundError: No module named 'inkex.paths'; 'inkex' is not a package_

- deprecation warnings for regmarks plot have changed
Bildschirmfoto von 2020-07-05 12-37-02

File: silhouette/Graphtec.py [hunk 1]
```diff
@@ -409,7 +409,7 @@ def read(s, size=64, timeout=5000):
     elif isinstance(data, bytearray):
         return str(data).decode()
     else:
-        return data.tostring().decode()
+        return data.tobytes().decode()  # return data.tostring().decode()
```
Comment (t0b3) [inline silhouette/Graphtec.py:412]: not compatible with python2:
AttributeError: 'array.array' object has no attribute 'tobytes'

thus another solution is needed to keep compatiblity with python2

**Comment by uxwalter** [comment]
I have no means to check with python2 anymore, I could blindly add a "if PY3" around the one line change without verification.

I'd encourage you to read up on https://www.python.org/doc/sunset-python-2/ and consider changing direction to retain Python2 compatibility. Especially the part about security concerns.

**Comment by t0b3** [comment]
@uxwalter I neither do. I personally would like to push forward.
Still I believe it's important to be aware of breaking changes, as I understood the maintainers still have use cases with Inkscape < 1.0.

To make sure any changes keep all the possible inkscape/python/os combinations running, I propose a PR to introduce continuous integration tests (#99).
image
NB: You may enable those tests by creating a travis-ci account and enabling travis on your github inkscape fork. This enables you to oversee the impact of code commits.

**Comment by t0b3** [comment]
@EtherGraf would you still like to keep compatibility with python2 and Inkscape < 1?

If yes
* I propose to use 
`try: [...inkscape1_functions...]   #inkscape1.0`
`except: [...legacy_functions...]   #inkscape 0.95` 
patterns like these https://github.com/t0b3/inkscape-silhouette/blob/65aa3e2302701c741c56b219fd93dba0a7e65766/sendto_silhouette.py#L277-L373

If no 
* I presume it's ok to introduce some breaking changes like the ones proposed in this PR.

**Comment by EtherGraf** [comment]
I agree, we need to be compatible with Inkscape 1.0 as soon as possible. 
My personal working environment is based on Xubuntu 18.08 and Inkscape 0.92.3 with PY2. So I think we should be compatible with PY2 at least until the extension is working fine with Inkscape 1.0

I see some possibilities to achieve this:
1. We do a fork and let the legacy PY2 stuff behind us in the old project.
2. We enclose the incompatible code in constructs like if PY2 ... else ... / try ... catch...
3. We introduce some compatibility layer where we hide the PY2/PY3 stuff.

I don't like the example you have given above, as it doubles the whole argument parser code. I think this is error prone for future development. It's not easy to oversee all such branches in future maintenance.

Is there no option parser which is supported in PY2 and PY3?
Would it be thinkable to write a wrapper function call, which delegates to the appropriate option parser?
Then the programm logic gets written down only one time.
e.g.

function addOption():
  if PY2 then:
    ... oldOptionParser.add
  else:
    ...newOptionParser.add

**Comment by EtherGraf** [comment]
From my long running software projects I have a further tip:
In such cases I prefer to use the old version in the if condition:

e.g.
if PY2 then...
else...

and NOT 
if PY3...
else....

This has two advances. First I can extend the list
if PY2...
if PY3...
if PY4...

Second i can with small effort remove all legacy stuff: Simply remove all PY2 clauses.

**Comment by t0b3** [comment]
I can confirm we are already compatible with Python 3 and Inkscape 0.92.5.
(my personal workspace) and thoroughly tested with Travis Continuous
Integration Tests.
To make this results public I suggest to merge PR #99 and create a free
Travis account for this project. This decision really won't do any harm.
Can you agree to this or would you like more detailed information?

I like your proposition to introduce
if PY2; if PY3
patterns. Unfortunately things will become more complicated as it's mainly
not PY3 but Inkscape 1.0 introducing breaking API changes. That is why I
went for patterns
try #inkscape 1.0...

OTOH it would be easier for maintenance to go for a separate branch without
all the legacy.


EtherGraf <notifications@github.com> schrieb am Sa., 18. Juli 2020, 10:55:

**Comment by twmr** [comment]
I had to apply the following patch on top of this PR to fix an issue that I had with the extension.

```diff
diff --git a/sendto_silhouette.py b/sendto_silhouette.py
index 4050cf9..00d83ba 100644
--- a/sendto_silhouette.py
+++ b/sendto_silhouette.py
@@ -631,12 +631,12 @@ class SendtoSilhouette(inkex.Effect):
                                         if t:
                                                 newpath.set( 'transform', t )
                                         a = []
-                                        a.append( ['M ', [x, y]] )
-                                        a.append( [' l ', [w, 0]] )
-                                        a.append( [' l ', [0, h]] )
-                                        a.append( [' l ', [-w, 0]] )
-                                        a.append( [' Z', []] )
-                                        newpath.set( 'd', simplepath.formatPath( a ) )
+                                        a.append( ['M', [x, y]] )
+                                        a.append( ['l', [w, 0]] )
+                                        a.append( ['l', [0, h]] )
+                                        a.append( ['l', [-w, 0]] )
+                                        a.append( ['Z', []] )
+                                        newpath.set( 'd', str(Path( a ) ))
                                         self.plotPath( newpath, transform )
 
                         elif node.tag == inkex.addNS( 'line', 'svg' ) or node.tag == 'line':
```

**Comment by tuxfunk** [comment]
I'm not sure if I'm applied the fixes correctly, but I was able to cut again with Inkscape 1.0.1 (not possible before with the official plugin). But I noticed a problem: I positioned a complex object (airbrush masks) in the upper right corner on the page. The object was correctly cut in size, but on the upper left corner of the page, so the position on the page was ignored somehow.
Thanks!

**Comment by uxwalter** [comment]
I made an update a while ago that I figured I share here. The plot routine never applied any transform to the path being plotted which caused a number of issues. I lifted a few lines of code from gcodetools.py which is part of inkscape.

For starters, the awkward change to the unit to pixel math is now gone which makes a whole lot more sense. I assume that happened because my default unit is inches and the conversion from inches to mm never happened (but inches to pixels is 1-1). Just a guess but since it's working now without my previous change I won't fret about it.

@bianchifan : Probably more important is that your input file now renders correctly as far as I can tell. Give it a shot and let me know.

**Comment by jnweiger** [comment]
I have not yet seen a nice exmples how to keep compatible with old py2 0.92.x inkscape at the same time as introducing 1.0 compatibility. 
I agree that readability suffers as we sprincle the code with if py2/ if py3, --- I have already done that pattern in other projects and I think it is acceptible. 
If nothing else helps, let us break compatibility with inkscape 0.92.x and move forward. 

@t0b3 I've invited you to join the team, 
@EtherGraf you had only writer, I made you maintainer now.

I'd love to see CI here too!

Sorry that I do so little myself, it really worries me that I can only create stuff and then apparently have to dump the maintenance burden on others. Sincerely sorry fo that bad behaviour on my side!

File: silhouette/Graphtec.py (hunk 1 above)
Comment (t0b3) [reply silhouette/Graphtec.py:412]: resolved in master:
`try: ...tobytes()... exept: ...tostring()...`

**Comment by t0b3** [comment]
@jnweiger thank you for resending the invitation to the team. 
@uxwalter huge thanks for bringing up a working solution for Inkscape 1.0.

Finally I managed to get some time and to
- [x] make the code compatible to run with any Inkscape version. see latest code in master. with this code, choice is up to the people when to make the transition to Inkscape 1.0
- [x] make the basic tests run on any platform. see https://travis-ci.com/github/fablabnbg/inkscape-silhouette for more details.

You are very welcome to provide more tests. Also let me know your feedback.

**Comment by t0b3** [comment]
@thisch @tuxfunk you are welcome to try with the latest code in master and let me know your feedback. 
as far as currently introduced tests tell the basic parts of the code work on any Inkscape version https://travis-ci.com/github/fablabnbg/inkscape-silhouette - but these are just the basic tests. Feel free to propose more tests ...
