### ISSUE TITLE
Get inkscape-silhouette to work on Inkscape 1.0

### ISSUE THREAD

**Issue by probonopd** [fablabnbg/inkscape-silhouette#84]
```
wget -c https://github.com/fablabnbg/inkscape-silhouette/archive/master.tar.gz
tar xf  master.tar.gz
mkdir -p $HOME/.config/inkscape/extensions/
cp -r inkscape-silhouette-master/* $HOME/.config/inkscape/extensions/
apt download python-usb
dpkg -x python-usb*.deb .
cp -r ./usr/lib/python2.7/dist-packages/usb $HOME/.config/inkscape/extensions/
sudo su
cat > /etc/udev/rules.d/99-graphtec-silhouette.rules <<\EOF
SUBSYSTEM=="usb", ATTR{idVendor}=="0b4d", ATTR{idProduct}=="1123", MODE="666"
EOF
udevadm trigger
```

When I run the [latest Inkscape continuous build as of today](https://gitlab.com/inkscape/inkscape/-/jobs/235967907/artifacts/raw/Inkscape-65a7af4-x86_64.AppImage) and try to send something to the Silhouette, I get

```
sendto_silhouette.py:121: DeprecationWarning: inkex.localize was moved to inkex.localization.localize
  inkex.localize()	# 0.91
Traceback (most recent call last):
  File "sendto_silhouette.py", line 1163, in <module>
    e = SendtoSilhouette()
  File "sendto_silhouette.py", line 229, in __init__
    inkex.Effect.__init__(self)
  File "/tmp/.mount_Inksca61sbQl/usr/share/inkscape/extensions/inkex/base.py", line 169, in __init__
    super(SvgInputMixin, self).__init__()
  File "/tmp/.mount_Inksca61sbQl/usr/share/inkscape/extensions/inkex/deprecated.py", line 74, in __init__
    self.svg = inkex.svg.SvgDocumentElement()
AttributeError: 'module' object has no attribute 'svg'
```

`/tmp/.mount_Inksca61sbQl/usr/share/inkscape/extensions/inkex/svg.py` does exist.

I am still not 100% sure whether this is an Inkscape 1.0 related issue or whether this is an AppImage packaging related issue, so any hints on how to get the Silhouette going with https://gitlab.com/inkscape/inkscape/-/jobs/235967907/artifacts/raw/Inkscape-65a7af4-x86_64.AppImage (or what needs to be changed therein) would be highly appreciated. Maybe @doctormo knows what is going wrong here?

References:
* https://gitlab.com/inkscape/extensions/issues/38
* https://github.com/fablabnbg/inkscape-silhouette/issues/30

**Comment by t0b3** [comment]
@probonopd @doctormo you are welcome to test the latest master and provide feedback or open new issues.
The code works now with any Inkscape version. See https://travis-ci.com/github/fablabnbg/inkscape-silhouette for more details on newly introduced tests.
